### ISSUE TITLE
Wrong tokens genereated 

### ISSUE THREAD

**Issue by bhrg3se** [d-band/RnTotp#2]

**Comment by bhrg3se** [comment]
I fixed it by replacing botp package with otp-client package

**Comment by helloyou2012** [comment]
@bhrg3se could you provide some test cases?

**Comment by bhrg3se** [comment]
When I encoded some string from terminal and generated otp codes, it works fine. But when I try to generate otp from google it doesn't works. So I replaced botp library with otp-client library. Now it works fine.
